name: tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Lint
        run: golint -set_exit_status ./...

      - name: Test
        run: go test -v ./...

      - name: Vet
        run: go vet ./...
